<?php
session_start();
include("headers.php");
include("dbconnection.php");

?>

<div class="wrapper col2">
  <div id="breadcrumb">
    <ul>
      <li class="first">View New Complaint Box</li></ul>
  </div>
</div>
<div class="wrapper col4">
  <div id="container">
    <h1>View New Complaint Box</h1>
    <form method="post" action="">
      <table width="692" border="3">
        <tbody>
          <tr>
            <td width="71">Complaining Dept.</td>
            <td width="52">Comp.Type</td>
           
            <td width="82">Generated By</td>
            <td width="43">Assigned To</td>
            <td width="43">Complaint St.</td>
     
          </tr>
          <?php
		$sql ="SELECT * FROM  complaint_details where status='Active'";
		
		
		$qsql = mysqli_query($con,$sql);
		while($rs = mysqli_fetch_array($qsql))
		{
			$sqlpat = "SELECT * FROM department WHERE departmentid ='$rs[department]'";
			$qsqlpat = mysqli_query($con,$sqlpat);
			$rspat = mysqli_fetch_array($qsqlpat);
			
        echo "<tr>
           <td>&nbsp;$rspat[departmentname]</td>
		   <td>&nbsp;$rs[complain_type]</td>
		   
			<td>&nbsp;$rs[generated_by]</td>
			 <td>&nbsp;$rs[assigned_to]</td>
			  <td>&nbsp;$rs[status]</td>";   
	
       echo " </tr>";
		}
		?>
        </tbody>
      </table>
    </form>
    <p>&nbsp;</p>
  </div>
</div>
</div>
 <div class="clear"></div>
  </div>
</div>
<?php
include("footers.php");
?>